### ISSUE TITLE
[DOCS]: Invalid Discord link

### ISSUE THREAD

**Issue by esau-morais** [bridge-codes/bridge#4]
### Description
It seems like the Discord link is broken

### Screenshots
![invite invalid](https://user-images.githubusercontent.com/55207584/218130248-074f2073-5a94-4b60-bd4f-ba39c0d5e30a.png)

**Comment by esau-morais** [comment]
[Correct Link](https://discord.com/invite/yxjrwm7Bfr)

**Comment by esau-morais** [comment]
If it is needed, I can update the GitHub documentation

**Comment by raulmihaila** [comment]
Please go on 👍
